parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\:
        resource: '../src/Service/*'

    App\Command\WorldCommand:
        arguments:
            - "@kernel"
        tags:
            - { name: 'console.command'}